# Generated by Django 5.1.6 on 2025-08-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=10)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('columnas', models.TextField()),
                ('filas', models.IntegerField()),
            ],
        ),
    ]
