# Generated by Django 5.1.6 on 2025-08-27 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoDetectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del archivo')),
                ('ruta_completa', models.CharField(max_length=1000, verbose_name='Ruta completa')),
                ('tipo', models.CharField(choices=[('excel', 'Excel (.xlsx, .xls)'), ('csv', 'CSV (.csv)'), ('txt', 'Texto (.txt)')], max_length=10, verbose_name='Tipo de archivo')),
                ('tamaño', models.BigIntegerField(verbose_name='Tamaño en bytes')),
                ('fecha_modificacion', models.DateTimeField(verbose_name='Fecha de modificación')),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de detección')),
                ('hojas', models.TextField(blank=True, null=True, verbose_name='Hojas disponibles (JSON)')),
            ],
            options={
                'verbose_name': 'Archivo Detectado',
                'verbose_name_plural': 'Archivos Detectados',
            },
        ),
        migrations.CreateModel(
            name='CarpetaCompartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la carpeta')),
                ('ruta', models.CharField(max_length=500, verbose_name='Ruta de la carpeta compartida')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carpeta Compartida',
                'verbose_name_plural': 'Carpetas Compartidas',
            },
        ),
        migrations.CreateModel(
            name='ArchivoProcesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoja_seleccionada', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hoja seleccionada')),
                ('filas_totales', models.IntegerField(verbose_name='Total de filas')),
                ('columnas_totales', models.IntegerField(verbose_name='Total de columnas')),
                ('columnas_nombres', models.TextField(verbose_name='Nombres de columnas')),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('datos_preview', models.TextField(verbose_name='Preview de datos (JSON)')),
                ('archivo_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesados', to='archivos.archivodetectado')),
            ],
            options={
                'verbose_name': 'Archivo Procesado',
                'verbose_name_plural': 'Archivos Procesados',
            },
        ),
        migrations.AddField(
            model_name='archivodetectado',
            name='carpeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='archivos.carpetacompartida'),
        ),
        migrations.AlterUniqueTogether(
            name='archivodetectado',
            unique_together={('carpeta', 'ruta_completa')},
        ),
    ]
