# Generated by Django 4.2.23 on 2025-09-04 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0002_archivodetectado_carpetacompartida_archivoprocesado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('json_config', models.JSONField()),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('exito', models.BooleanField(default=False)),
                ('filas_totales', models.IntegerField(default=0)),
                ('mensaje', models.TextField(blank=True)),
                ('errores', models.JSONField(blank=True, null=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='archivos.processconfig')),
            ],
        ),
    ]
